### PR TITLE
Added basic macOS support.

### PR DESCRIPTION
**Pull request by brandonmbare**

### CODE REVIEW

**Comment by brandonmbare** [comment]
This doesn't make a whole lot of sense.  I'm testing it on linux right now and the test is passing just fine...

**Comment by ShadauxCat** [comment]
The default architecture is returning 32bit. I checked on my surface and a 32-bit python executable returns 32-bit from `platform.architecture()`. Not sure how I ended up with a 32-bit python executable, but I don't think we can rely on `platform.architecture()` to determine if the OS is 64bit or not. We need to find another option.

Double check whether the python executables on your build machine are 64bit.

**Comment by brandonmbare** [comment]
That's technically correct behavior, but I see your point.  The builds were fixed by installing libc6-dev-i386, which somehow wasn't present before now.  I have no idea how that test worked before, but that fixes it.  I'll deal with the system architecture thing as a separate issue since it doesn't really affect this change.  Also, nice work getting those build checks in place.  Very handy.

**Comment by ShadauxCat** [comment]
That isn't the correct fix. They should not be running x86 builds in the first place. The fact that they are represents a bug with csbuild. But I'll accept this PR.

**Comment by brandonmbare** [comment]
That test is explicitly building for x86...

**Comment by brandonmbare** [comment]
`self.assertMakeSucceeds("-v", "--arch=x86", "--project=hello_world", "--show-commands")`

**Comment by ShadauxCat** [comment]
Oh. That explains it then. Then I guess installing those things was the correct fix. Nevermind!

**Pull request merged**
